baseURL: ""
languageCode: "en-us"
title: "Masu Portfolio"
theme: ["hugo-chart", "hugo-profile"]

Paginate: 3
disqusShortname: masu-portfolio

markup:
  goldmark:
    renderer:
      unsafe: true


Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/images/cat.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Masuda."
    subtitle: "An unemployed student in search of a job :("
    content: "I like creating visually pleasing 3D art and websites for fun. Someone please hire me. Or as a tutor."
    image: https://nitter.net/pic/orig/media%2FFP6K8NyaUAQNmRn.jpg
    button:
      enable: true
      name: "Resume"
      url: https://docs.google.com/document/d/18xdEILV8LsWfrV4pFT190crNUPccdL57/edit?usp=sharing&ouid=110105006431998175542&rtpof=true&sd=true
      download: true 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Medushaa
        - icon: fab fa-instagram
          url: https://www.instagram.com/masuda_masu/
        - icon: fab fa-behance
          url: https://www.behance.net/masudarahman

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am currently undergraduate student doing a double major in Computer Science and Mathematics in Bangladesh. My hobbies include creating cute models in Blender 3D, illustrations in Adobe illustrator and customising static websites.
      
      Apart from drowning myself in artsy ambitions, i also enjoy tutoring students and involving myself in computer science related projects.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Blender"
        - "Flutter"
        - "Adobe Illustrator"
        - "LaTeX"
        - "Python"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Student Tutor at BracU"
        company: "BracU ST"
        companyUrl: "https://www.bracu.ac.bd/"
        date: "Jan 2022 - present"
        info:
          enable: false
        content: |
          MAT110 (Calculus): Assisted the faculty in handing the gradesheet, making question papers and helping students with technical issues with their online learning platform, BuX.
          
          MAT215 (Complex Variables and Laplace Transformation): Checked assignment copies and lab code submissions in 2 sections with total 80 students.

          MAT215 (Mathematics for Machine Learning): Same as above, plus giving consultations for 9 hours a week.

          MAT222 (Differential Equations 1)

          MAT205 (Numerical Analysis)

          MAT216 (Linear Algebra and Fourier Transformation)

          MAT123 (Calculus I)
          

      - job: "Private tutor for O and A level Students"
        company: "Private Tutor"
        date: "Sep 2018 - Present"
        info:
          enable: false
          content: 
        content: |
          Started tutoring a friend during my A levels and that lead to getting requests to tutor from more of my juniors.

          Till now, I have tutored over 7 students individually in subjects that I have myself completed in my O and A levels.

      - job: "Senior Executive of IT dept at ROBU club"
        company: "ROBU"
        date: "Sep 2020 - Present"
        info:
          enable: false
          content: 
        content: |
          Created posters and animated videos for the club's [social media page](https://www.facebook.com/BRACU.Robotics.Club).

          Was appointed as an instructor in a workshop for Introduction to Blender and 3D art.
        


  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Bachelor of Science in Computer Science and Mathematics"
        school:
          name: "BRAC University"
          url: "https://www.bracu.ac.bd/"
        date: "2020 - Present"
        GPA: "3.9 out of 4.0"
        featuredLink:
          enable: true
          name: "Courses taken and Results"
          url: "/blogs/grades"
          # url: "https://docs.google.com/spreadsheets/d/1a4n7q1-kpxSzgP3INtT8YbP9NQYiq7zvB9cqygihWcs/edit?usp=sharing"

      - title: "High School"
        school:
          name: "East West International School and College"
          url: "http://east-westintlsc.com/"
        GPA: "5 out of 5"
        content: |-
          O Level grades (Edexcel):
          - A* in: Mathematics A, Mathematics B, Further Pure Mathematics, Physics, Chemistry, Biology, Human Biology, Bangla
          - A in: English
          - World Highest in Mathematics A

          A Level grades (Edexcel):
          - A* in General Mathematics, Further Pure Mathematics, Biology, Physics
          - A in Chemistry and C in Psychology
      

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Website using Three.js
        content: A cute pastel website with moving 3D objects in the background that can be interacted with by scrolling.
        image: /images/threeJs.jpg
        featured:
          name: Site link
          link: https://three-js-pastel-site.netlify.app/
        badges:
          - "Three.js"


      - title: Flutter App to Track expiry dates
        content: where users can create an account, add items to their list, and create public blogs.
          Flutter and Firebase was used to create this app for a course project.
        image: /images/foodUm.png
        featured:
          name: Download Apk
          link: https://drive.google.com/file/d/1QMDyiGAVmVxDjnxOVxdc6Jn3YTl2ip6K/view?usp=sharing
        links:
          - icon: fab fa-github
            url: https://github.com/Medushaa/cse471-project-flutter

      - title: Weekly Blender arts
        content: | 
          I have been doing a challenge where I post one blender art every wednesday since the pandemic started. It helped me connect with other artists and encorage them to do the same.
        image: /images/Portfolio/Borger.png
        featured:
          name: Behance Profile
          link: https://www.behance.net/masudarahman
        links:
          - icon: fab fa-behance
            url: https://www.behance.net/masudarahman
        badges:
          - "3D models"
          - "Animation"


      - title: Note sharing Website
        content: |
          It's a website where people can login and share notes as links or pdf. Also they can like and comment these posts.
          This was done with Laravel.
        image: /images/laravel.png
        badges:
          - "Laravel"
          - "MySQL"
        links:
          - icon: fab fa-github
            url: https://github.com/Medushaa/Note-sharing-site-CSE470

      - title: Discord bot
        content: |
          A discord bot to go through assignment marks in csv file and DM the respective students. 
          Also, can plot graphs. Coded in python.  
        image: /images/discord-bot.png
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/Medushaa/st-masu-bot

      - title: ToDo Flutter App
        content: Add tasks, delete tasks, crossout tasks, search task. Offline app, so firebase wasn't needed/
        image: /images/tod_app.jpg
        featured:
          name: Download Apk
          link: https://drive.google.com/file/d/1yWd6stJJN-zrlSXgWDrV-oeT7HuOAvCO/view?usp=sharing
        badges:
          - "Flutter"
          - "Adroid App"
        links:
          - icon: fab fa-github
            url: https://github.com/Medushaa/ToDo-list-Flutter-App





  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: masudarahman88@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Medushaa
      linkedin: https://www.linkedin.com/in/masuda-rahman-fatima-2a694b208/
      instagram: https://www.instagram.com/masuda_masu/
      facebook: https://www.facebook.com/masu.masuda.masu/
